---
leaf1:
  hostname: 192.168.1.1
  username: admin
  password: admin
  platform: eos
  groups:
    - leaf
leaf2:
  hostname: 192.168.1.2
  username: admin
  password: admin
  platform: eos
  groups:
    - leaf
spine1:
  hostname: 192.168.1.3
  username: admin
  password: admin
  platform: eos
  groups:
    - spine
spine2:
  hostname: 192.168.1.4
  username: admin
  password: admin
  platform: eos
  groups:
    - spine
